[[codeprimate-build]]
= Codeprimate Build
:version: 2.0.0-M7


The Codeprimate Build project (or simply, "The Build"; `org.codeprimate.build:maven-build`) is a Maven project
used to build and release all Codeprimate software.

[[requirements]]
== Requirements

1. Baseline is Java SE (JDK/JRE) 17.
2. Built with Oracle JDK 17.0.8 2023-07-18 LTS
2.1 Builds with Oracle JDK 21 2023-09-19 LTS

[[license]]
== License

*Build* is licensed under the **Apache 2.0 Software License Agreement**.

[[download]]
== Download / Include

.Maven
====
[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.codeprimate.build</groupId>
  <artifactId>maven-build</artifactId>
  <version>{version}</version>
</dependency>
----
====

[[issues]]
== Issues

Please use https://github.com/codeprimate-software/cp-build/issues[GitHub Issues] to report any bugs, improvements
or feature requests.

[[contributions]]
== Contributions

Thank you for your interests in contributing to the *Codeprimate Build* project.  A full *contributor license agreement*
(CLA) along with details on how to contribute to this project will be provided shortly.

In the meantime, please submit tickets using https://github.com/codeprimate-software/cp-build/issues[GitHub Issues]
or PRs using https://github.com/codeprimate-software/cp-build/pulls[GitHub Pull Requests].

**Thank you!**
