[[codeprimate-build]]
= Codeprimate Build
:version: 2.0.0


The Codeprimate Build project (or simply, "The Build"; `org.codeprimate.build:maven-build`) is a Maven project using Apache Maven to build and release all Codeprimate software.

[[requirements]]
== Requirements

1. Baseline is Java SE (JDK/JRE) 17.
2. Built with Oracle JDK 17.0.18 2026-01-20 LTS LTS (build 17.0.18+8-LTS-264)
3. Builds with Oracle JDK 21 2026-04-21 LTS (build 21.0.11+9-LTS-211)
4. Builds with Apache Maven 3.9.16 (Apache Maven Wrapper 3.3.4)

[[license]]
== License

*Build* is licensed under the **Apache 2.0 Software License Agreement**.

[[download]]
== Download / Include

.Maven
====
[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.codeprimate.build</groupId>
  <artifactId>maven-build</artifactId>
  <version>{version}</version>
</dependency>
----
====

[[issues]]
== Issues

Please use https://github.com/codeprimate-software/cp-build/issues[GitHub Issues] to report any bugs, improvements or feature requests.

[[contributions]]
== Contributions

Thank you for your interests in contributing to the *Codeprimate Build* project.  A full *contributor license agreement* (CLA) along with details on how to contribute to this project will be provided shortly.

In the meantime, please submit tickets using https://github.com/codeprimate-software/cp-build/issues[GitHub Issues] or PRs using https://github.com/codeprimate-software/cp-build/pulls[GitHub Pull Requests].

**Thank you!**
